services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    privileged: true
    ports:
      - "8080:8080"   # WebSwing Web UI (browser-based interface)
      - "8090:8090"   # ZAP Proxy & API port
    volumes:
      - ./zap:/zap/wrk/:rw   # Persist ZAP state
      - ./microservices-openapi300.yaml:/zap/wrk/microservices-openapi300.yaml
      - ./MicroServices.postman_collection.json:/zap/wrk/MicroServices.postman_collection.json
    environment:
      ZAP_WEBSWING_PORT: 8080         # Match exposed port
      ZAP_WEBSWING_HOST: 0.0.0.0      # Accept all incoming connections
    command: zap-webswing.sh
